### ISSUE TITLE
🐞: [BUG] Expected to decode Bool

### ISSUE THREAD

**Issue by iclems** [lukepistrol/TimeMachineStatus#17]
**Describe the bug**
Probably related to Time Machine Editor.

**To Reproduce**
1. Go to app
2. Shows 100% of the time

**Expected behavior**
Only shows an error when opening

**Screenshots**
<img width="336" alt="image" src="https://github.com/lukepistrol/TimeMachineStatus/assets/1120050/e4fb8fc9-786a-4b46-b7ff-e8d39ff8e767">

**Additional context**

**Comment by iclems** [comment]
Sorry for filing this, bought you a coffee to apologise for the noise :-) I can probably take a look at the code in a couple of weeks myself to debug if you need help

**Comment by lukepistrol** [comment]
Thx for submitting the bug and for the coffee of course!

Looks like the `RequiresACPower` value in `/Library/Preferences/com.apple.TimeMachine.plist` is neither `0` nor `1` in your case. Could you please share what value it is in your case?

Maybe I need to change [this](https://github.com/lukepistrol/TimeMachineStatus/blob/b14769d534db6f8fca08a0a496baf5c3f2dca7ad/TimeMachineStatus/Model/Preferences/Preferences.swift#L32C18-L32C18) to an enum of some sort instead of a boolean.

It would be interesting to know what possible values there could be.

**Comment by iclems** [comment]
For some weird reason it’s a string here: 
￼

**Comment by lukepistrol** [comment]
And what string?
Which device are you on?
Any special energy related settings?

I tried on both my Mac Mini and (Intel) MacBook Pro and couldn't reproduce it unfortunately. The checkbox in Time Machine Settings for backing up on battery power only changes the value to either 0 or 1. And energy related settings like Power Nap have no impact on the value.

**Comment by iclems** [comment]
It’s actually a 0 (I attached a screenshot earlier) but set as a string.
Maybe a tool I used tricked it… unfortunately it’s hard to unlock this file
to edit manually

Clément


Le mar. 9 janv. 2024 à 12:29, Lukas Pistrol ***@***.***> a
écrit :

**Comment by lukepistrol** [comment]
Ok then something messed up your time machine preferences.

To fix this you can simply run this in Terminal:

```sh
sudo defaults write /Library/Preferences/com.apple.TimeMachine.plist RequiresACPower -bool NO
```
